#!/bin/sh
 
/busybox mount -t proc none /proc
/busybox mount -t sysfs none /sys
/busybox mount -t debugfs none /sys/kernel/debug
/busybox mount /dev -t devtmpfs dev

/busybox echo -e "\nBoot took $(/busybox cut -d' ' -f1 /proc/uptime) seconds\n"
 
if [ -f /user_prog ]; then
    /user_prog;
fi

exec /busybox sh
