from _typeshed import Incomplete

class TaintQuery:
    num_labels: Incomplete
    tcn: Incomplete
    cb_mask: Incomplete
    qr: Incomplete
    taint2: Incomplete
    no_more: bool
    ffi: Incomplete
    def __init__(self, query_result, panda_taint2, ffi) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    def get_labels(self): ...
    def reset(self) -> None: ...
