from exert.utilities.types.multi_arch import CPUState

class PandaArch:
    def get_reg(self, cpu: CPUState, reg: str) -> int: ...
    def set_reg(self, cpu, reg, val): ...
    def get_pc(self, cpu): ...
    def get_arg(self, cpu: CPUState, idx: int, convention: str = 'default') -> int: ...
    def set_pc(self, cpu, val): ...

class ArmArch(PandaArch):
    def get_return_value(self, cpu): ...
    def get_return_address(self, cpu): ...

class Aarch64Arch(PandaArch):
    def get_pc(self, cpu): ...
    def get_return_value(self, cpu): ...
    def get_return_address(self, cpu): ...

class MipsArch(PandaArch):
    def get_reg(self, cpu, reg): ...
    def get_pc(self, cpu): ...
    def get_call_return(self, cpu): ...
    def get_return_address(self, cpu): ...

class PowerPCArch(PandaArch):
    def get_pc(self, cpu): ...
    def get_reg(self, cpu, reg): ...

class X86_64Arch(PandaArch):
    def get_pc(self, cpu): ...
    def get_return_value(self, cpu): ...
    def get_return_address(self, cpu): ...
    def get_reg(self, cpu, reg): ...
    def set_reg(self, cpu, reg, val): ...
