from exert.utilities.types.multi_arch import CPUState

class PandaArch:
    def get_reg(self, cpu: CPUState, reg: str) -> int: ...
    def get_arg(self, cpu: CPUState, idx: int, convention: str = 'default') -> int: ...
