from _typeshed import Incomplete
from pandare.utils import debug as debug, warn as warn

# def progress(msg) -> None: ...

class AsyncThread:
    running: bool
    panda_started: Incomplete
    task_queue: Incomplete
    athread: Incomplete
    warned: bool
    ending: bool
    empty_at: Incomplete
    last_called: Incomplete
    # def __init__(self, panda_started) -> None: ...
    def stop(self) -> None: ...
    # def queue(self, func, internal: bool = False) -> None: ...
    # def run(self, task_queue, internal: bool = False) -> None: ...

def test1() -> None: ...
def test2() -> None: ...
def test3() -> None: ...
