from _typeshed import Incomplete
from colorama import Fore as Fore, Style as Style

class TimeoutExpired(Exception): ...

class Expect:
    name: Incomplete
    logfile: Incomplete
    fd: Incomplete
    prior_lines: Incomplete
    current_line: Incomplete
    last_msg: Incomplete
    running: bool
    cleared: bool
    consumed_first: Incomplete
    use_unansi: Incomplete
    last_prompt: Incomplete
    expectation_re: Incomplete
    expectation_ends_re: Incomplete
    poller: Incomplete
    def is_connected(self): ...
    def __del__(self) -> None: ...
    def abort(self) -> None: ...
    def consume_partial(self): ...
    def get_partial(self): ...
    def unansi(self) -> None: ...
    def send_eol(self) -> None: ...
    def sendline(self, msg: bytes = b'') -> None: ...
