from colorama import Fore as Fore, Style as Style

class TimeoutExpired(Exception): ...

class Expect:
    running: bool
    cleared: bool
    def __del__(self) -> None: ...
    def abort(self) -> None: ...
    def unansi(self) -> None: ...
    def send_eol(self) -> None: ...
    def sendline(self, msg: bytes = b'') -> None: ...
