from _typeshed import Incomplete

class PLogReader:
    f: Incomplete
    chunks: Incomplete
    chunk_idx: int
    chunk_size: int
    chunk_data: Incomplete
    chunk_data_idx: int
    def __init__(self, fn) -> None: ...
    def __iter__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb) -> None: ...
    def __next__(self): ...
