from _typeshed import Incomplete

class _PPP_CB:
    callbacks: Incomplete
    def __init__(self) -> None: ...
    def run(self, *args) -> None: ...
    def add_callback(self, fn) -> None: ...

class PyPlugin:
    def __init__(self, panda) -> None: ...
    ppp_cbs: Incomplete
    args: Incomplete
    pypluginmgr: Incomplete
    def __preinit__(self, pypluginmgr, args) -> None: ...
    @property
    def ppp(self): ...
    @staticmethod
    def ppp_export(method): ...
    def get_arg(self, arg_name): ...
    def get_arg_bool(self, arg_name): ...
    def ppp_cb_boilerplate(self, cb_name) -> None: ...
    def ppp_run_cb(self, target_ppp, *args) -> None: ...
