from _typeshed import Incomplete

class QEMU_Log_Manager:
    panda: Incomplete
    log_members: Incomplete
    def __init__(self, panda) -> None: ...
    def enable(self, name) -> None: ...
    def disable(self, name) -> None: ...
    def output_to_file(self, file_name, append: bool = True) -> None: ...
    def remove_log_file(self) -> None: ...
    def output_to_stderr(self) -> None: ...
    def output_to_stout(self) -> None: ...
    def log(self, msg) -> None: ...
