from _typeshed import Incomplete

class QEMU_Log_Manager:
    panda: Incomplete
    log_members: Incomplete
    def remove_log_file(self) -> None: ...
    def output_to_stderr(self) -> None: ...
    def output_to_stout(self) -> None: ...
