from _typeshed import Incomplete
from os import dup as dup, getenv as getenv, path as path
from pandare.pyplugin import PyPlugin

debug: bool

def progress(msg) -> None: ...
def warn(msg) -> None: ...
def make_iso(directory, iso_path) -> None: ...
def telescope(panda, cpu, val) -> None: ...
def blocking(func): ...
def rr2_name(name): ...
def rr2_recording(name): ...
def rr2_contains_member(name, member): ...

class GArrayIterator:
    garray: Incomplete
    garray_len: Incomplete
    current_idx: int
    func: Incomplete
    cleanup_func: Incomplete
    def __init__(self, func, garray, garray_len, cleanup_fn) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    def __del__(self) -> None: ...

class plugin_list(dict[str, PyPlugin]):
    def __init__(self, panda) -> None: ...
    def __getitem__(self, plugin_name): ...

def find_build_dir(arch_name: Incomplete | None = None, find_executable: bool = False): ...
