from _typeshed import Incomplete
from os import dup as dup, getenv as getenv, path as path
from pandare.pyplugin import PyPlugin

debug: bool

def blocking(func): ...
def rr2_name(name): ...
def rr2_recording(name): ...
def rr2_contains_member(name, member): ...

class GArrayIterator:
    garray: Incomplete
    garray_len: Incomplete
    current_idx: int
    func: Incomplete
    cleanup_func: Incomplete
    def __iter__(self): ...
    def __next__(self): ...
    def __del__(self) -> None: ...

class plugin_list(dict[str, PyPlugin]):
    def __getitem__(self, plugin_name): ...
