name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    # container:
    #   image: pandare/panda
    #   volumes:
    #   - ./usermode:/mount
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Install dependencies
    #   run: |
    #     cd /mount
    #     ./setup.sh
    # - name: Running the test
    #   run: |
    #     pytest --cov=exert tests/
    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v3
    - name: Init EXERT
      run: |
        python exert.py init
    - name: Run Tests
      run: |
        python exert.py dev test