name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    container:
      image: pandare/panda
      volumes:
      - ${GITHUB_WORKSPACE}/usermode:/mount
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        ./setup.sh
    - name: Running the test
      run: |
        pylint
